// webui/src/components/Toast.tsx
import { For } from "solid-js";

import { store } from "../lib/store";

import "./Toast.css";

export default () => (
  <div class="toast-container">
    <For each={store.toasts}>
      {(toast) => (
        <div class={`toast toast-${toast.type}`} role="alert">
          <span>{toast.text}</span>
        </div>
      )}
    </For>
  </div>
);

// webui/src/components/Toast.svelte
<script lang="ts">
  import { store } from '../lib/store.svelte';
  import { flip } from 'svelte/animate';
  import { fly } from 'svelte/transition';
  import { cubicOut } from 'svelte/easing';
  import './Toast.css';
</script>
<div class="toast-container">
  {#each store.toasts as toast (toast.id)}
    <div
      class="toast toast-{toast.type}"
      animate:flip={{ duration: 300, easing: cubicOut }}
      in:fly={{ y: 20, duration: 300, easing: cubicOut }}
      out:fly={{ y: 10, duration: 200, opacity: 0 }}
      role="alert"
    >
      <span>{toast.text}</span>
    </div>
  {/each}
</div>
